"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const allTasks_1 = __importDefault(require("./allTasks"));
const createTask_1 = __importDefault(require("./toDoTask/createTask"));
const eraseTask_1 = __importDefault(require("./toDoTask/eraseTask"));
const updateTask_1 = __importDefault(require("./toDoTask/updateTask"));
const getEditTask_1 = __importDefault(require("./toDoTask/getEditTask"));
const newSubtask_1 = __importDefault(require("./subTask/newSubtask"));
const updateSubtask_1 = __importDefault(require("./subTask/updateSubtask"));
const removeSubtask_1 = __importDefault(require("./subTask/removeSubtask"));
const routes = express_1.Router();
routes.use('/task/all-tasks', allTasks_1.default);
routes.use('/task/new-todo', createTask_1.default);
routes.use('/task/erase-task', eraseTask_1.default);
routes.use('/task/update-task', updateTask_1.default);
routes.use('/edit-task', getEditTask_1.default);
routes.use('/task/new-subtask', newSubtask_1.default);
routes.use('/task/remove-subtask', removeSubtask_1.default);
routes.use('/task/update-subtask', updateSubtask_1.default);
exports.default = routes;
